sudo: false

language: python

python:
  - 3.4
  - 3.6
  - 3.8

install:
  - pip install codecov
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script:
  - py.test --cov=bldlib

after_success:
  - codecov
